#include <stdio.h>
#include <stdlib.h>
#include "lexer.h"
#include "hashtable.h"
#include "parseDef.h"

int main(int argc, char *argv[])
{
    if (argc != 3)
        exit(1);
    FILE *fp = fopen(argv[1], "r");
    int len = atoi(argv[2]);
    
    // printf("1\n");
    fillEnumToNonTerminal();
    fillEnumToTerminal();
    // printf("1\n");
    initLex(fp, len);
    // for(int i = 0; i < TERMINALS_COUNT; i++)
    //      printf("%s\n", enumToTerminal[i]);
    getStream();
    //printf("1\n");
    populateGrammar();
    //printf("1\n");
    int rno;
    printf("Enter rule number\n"); 
    scanf("%d", &rno);
    rhsOfGrammarRuleNode *n = rules[rno];
    while (n != NULL)
    {
        if (n->symbol.isTerminal)
            printf("%s\t", enumToTerminal[n->symbol.tno]);
        else
            printf("%s\t", enumToNonTerminal[n->symbol.ntno]);
        n = n->next;
    }
    printf("\n");

    // driver as per ma'am instructions

    printf("----------IMPLEMENTATION STATUS")
    while(1)
    {
        int menu =0;
        printf("--------------------------------------------------------MENU--------------------------------------------------------\n");
        printf(" 0. EXIT. \n" 
               " 1. To see your source code without COMMENTS.\n"
               " 2. Print the token list generated by the Lexer along with lexical errors (if any).\n"
               " 3. Print the total time taken by Lexer and Parser to verify the sytantic correctness.\n");
        printf("PLEASE ENTER YOUR CHOICE: %d", menu);

        switch (menu)
        {
        case 0:
            exit(0);
            break;
        case 1: 
            printf("");


        default:
            break;
        }
    }
}